--ЗўЮёзЂВс--
insert into FD_APPINFO (ID, DESCRIPTION, FD_APPINFOID, ROWSTAMP, APPKEY, APPNAME, CONTEXTPATH, DATABASEURL, ICON, IPADDRESS, PORT, APPTYPE, ORGID, SECURITYLEVEL, CREATEORGID, CONTAINERPATH, GLOBJPARENTID, INSTANCEENTITY, PARENTOBJECTBIZID, PARENTOBJECTNAME, PARENTSYSTABLEID)
values ('4028ef506b08a254016b21886cbe0003', 'ids-pm-web', null, '2173765', 'ids-pm-web', 'ids-pm-web', '/ids-pm-web', '', '', '192.168.111.160', '18280', '1', '', null, '', '<CLOB>', '', '', '', '', '');
